#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# Resumable SAM/BAM processing pipeline using Samtools and Docker.
#
# This script processes Bowtie2 SAM files and generates filtered BAM files.
#
# Main steps:
#   1) Convert SAM to BAM
#   2) Keep mapped reads only
#   3) Sort BAM files by genomic coordinates
#   4) Remove duplicate reads with samtools markdup
#   5) For paired-end reads, keep concordant/properly paired reads
#   6) Keep reads with MAPQ >= 20
#   7) Index final BAM files
#   8) Generate quickcheck, flagstat reports, and a summary table
#
# Input:
#   Directory containing .sam files.
#
# Expected filename patterns:
#   SAMPLE_PE_bt.sam   for paired-end alignments
#   SAMPLE_SE_bt.sam   for single-end alignments
#
# Output directories, created inside the input directory:
#   01_fixed_bam/
#   02_mapped_bam/
#   03_sorted_bam/
#   04_dedup_bam/
#   05_concordant_bam/
#   06_q20_bam/
#   07_logs/
#   08_qc/
#   09_summary/
#
# Usage:
#   bash scripts/05_process_mapped_reads.sh -d <sam_directory> -t <threads> -m <PE|SE|BOTH> [options]
#
# Examples:
#   bash scripts/05_process_mapped_reads.sh -d results/mapping/sam -t 8 -m BOTH
#   bash scripts/05_process_mapped_reads.sh -d results/mapping/sam -t 8 -m PE
#   bash scripts/05_process_mapped_reads.sh -d results/mapping/sam -t 8 -m BOTH --delete-sam
#
# Requirements:
#   - Docker
#   - SAM files generated by Bowtie2 or a compatible aligner
#
# Docker image:
#   - staphb/samtools
###############################################################################

show_help() {
    cat << EOF
Usage:
  bash scripts/05_process_mapped_reads.sh -d <directory> -t <threads> -m <PE|SE|BOTH> [options]

Required arguments:
  -d <directory>       Directory containing input .sam files
  -t <threads>         Number of threads to use
  -m <PE|SE|BOTH>      Library mode:
                         PE   = only paired-end files allowed
                         SE   = only single-end files allowed
                         BOTH = detect and process both

Optional arguments:
  -i <docker_image>    Docker image containing samtools
                       Default: staphb/samtools
  --delete-sam         Delete original .sam files after successful BAM generation
  -h, --help           Show this help message and exit

Behavior:
  - Detects PE or SE from each filename.
  - Uses the first token before "_" as the sample name.
  - Stops if:
      * a file does not clearly contain PE or SE in its filename
      * detected type conflicts with -m PE or -m SE
      * two files would generate the same sample base name
  - If intermediate files already exist, completed steps are skipped.
  - samtools markdup runs with a Docker memory limit equal to 80% of host RAM.

Examples:
  bash scripts/05_process_mapped_reads.sh -d results/mapping/sam -t 8 -m BOTH
  bash scripts/05_process_mapped_reads.sh -d results/mapping/sam -t 8 -m PE -i staphb/samtools
  bash scripts/05_process_mapped_reads.sh -d results/mapping/sam -t 8 -m BOTH --delete-sam
EOF
}

if [[ $# -eq 0 ]]; then
    show_help
    exit 1
fi

###############################################################################
# Default parameters
###############################################################################

DIR=""
THREADS=""
MODE=""
DOCKER_IMAGE="staphb/samtools"
DELETE_SAM=0

###############################################################################
# Parse command-line arguments
###############################################################################

while [[ $# -gt 0 ]]; do
    case "$1" in
        -d)
            DIR="${2:-}"
            shift 2
            ;;
        -t)
            THREADS="${2:-}"
            shift 2
            ;;
        -m)
            MODE="${2:-}"
            shift 2
            ;;
        -i)
            DOCKER_IMAGE="${2:-}"
            shift 2
            ;;
        --delete-sam)
            DELETE_SAM=1
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            echo "[ERROR] Unknown argument: $1" >&2
            echo
            show_help
            exit 1
            ;;
    esac
done

###############################################################################
# Validate arguments and dependencies
###############################################################################

if [[ -z "${DIR}" || -z "${THREADS}" || -z "${MODE}" ]]; then
    echo "[ERROR] Missing required arguments." >&2
    echo
    show_help
    exit 1
fi

if [[ ! -d "${DIR}" ]]; then
    echo "[ERROR] Directory not found: ${DIR}" >&2
    exit 1
fi

if ! [[ "${THREADS}" =~ ^[0-9]+$ ]]; then
    echo "[ERROR] Number of threads must be a positive integer." >&2
    exit 1
fi

MODE="$(echo "${MODE}" | tr '[:lower:]' '[:upper:]')"

if [[ "${MODE}" != "PE" && "${MODE}" != "SE" && "${MODE}" != "BOTH" ]]; then
    echo "[ERROR] Mode must be PE, SE, or BOTH." >&2
    exit 1
fi

command -v docker >/dev/null 2>&1 || {
    echo "[ERROR] Docker is not installed or not available in PATH." >&2
    exit 1
}

docker info >/dev/null 2>&1 || {
    echo "[ERROR] Docker is not running or is not available for the current user." >&2
    exit 1
}

if [[ ! -w "${DIR}" ]]; then
    echo "[ERROR] No write permission in directory: ${DIR}" >&2
    exit 1
fi

cd "${DIR}"

###############################################################################
# Docker and memory configuration
###############################################################################

DOCKER_UIDGID="$(id -u):$(id -g)"

MEMTOTAL_KB="$(awk '/MemTotal:/ {print $2}' /proc/meminfo)"
MARKDUP_MEMORY_MIB=$(( MEMTOTAL_KB * 80 / 100 / 1024 ))
MARKDUP_MEMORY="${MARKDUP_MEMORY_MIB}m"

###############################################################################
# Output directories
###############################################################################

FIXED_DIR="01_fixed_bam"
MAPPED_DIR="02_mapped_bam"
SORTED_DIR="03_sorted_bam"
DEDUP_DIR="04_dedup_bam"
CONCORDANT_DIR="05_concordant_bam"
Q20_DIR="06_q20_bam"
LOG_DIR="07_logs"
QC_DIR="08_qc"
SUMMARY_DIR="09_summary"

mkdir -p \
    "${FIXED_DIR}" \
    "${MAPPED_DIR}" \
    "${SORTED_DIR}" \
    "${DEDUP_DIR}" \
    "${CONCORDANT_DIR}" \
    "${Q20_DIR}" \
    "${LOG_DIR}" \
    "${QC_DIR}" \
    "${SUMMARY_DIR}"

SUMMARY_FILE="${SUMMARY_DIR}/pipeline_summary.tsv"

###############################################################################
# Helper functions
###############################################################################

run_docker_samtools() {
    docker run --rm \
        --user "${DOCKER_UIDGID}" \
        -v "$(pwd)":/data \
        -w /data \
        "${DOCKER_IMAGE}" \
        samtools "$@"
}

run_docker_shell() {
    docker run --rm \
        --user "${DOCKER_UIDGID}" \
        -v "$(pwd)":/data \
        -w /data \
        "${DOCKER_IMAGE}" \
        sh -c "$1"
}

run_docker_shell_markdup() {
    docker run --rm \
        --memory "${MARKDUP_MEMORY}" \
        --user "${DOCKER_UIDGID}" \
        -v "$(pwd)":/data \
        -w /data \
        "${DOCKER_IMAGE}" \
        sh -c "$1"
}

file_ready() {
    local f="$1"
    [[ -s "${f}" ]]
}

extract_base_name() {
    local filepath="$1"
    local filename
    filename="$(basename "${filepath}")"
    echo "${filename%%_*}"
}

detect_library_type() {
    local filepath="$1"
    local filename
    filename="$(basename "${filepath}")"

    local has_pe=0
    local has_se=0

    if [[ "${filename}" =~ (^|[^A-Za-z0-9])PE([^A-Za-z0-9]|$) ]]; then
        has_pe=1
    fi

    if [[ "${filename}" =~ (^|[^A-Za-z0-9])SE([^A-Za-z0-9]|$) ]]; then
        has_se=1
    fi

    if [[ "${has_pe}" -eq 1 && "${has_se}" -eq 0 ]]; then
        echo "PE"
    elif [[ "${has_se}" -eq 1 && "${has_pe}" -eq 0 ]]; then
        echo "SE"
    elif [[ "${has_pe}" -eq 1 && "${has_se}" -eq 1 ]]; then
        echo "[ERROR] Could not determine library type uniquely for file: ${filename}" >&2
        return 1
    else
        echo "[ERROR] Could not detect PE or SE in filename: ${filename}" >&2
        return 1
    fi
}

validate_mode_vs_filetype() {
    local detected_type="$1"
    local filename="$2"

    if [[ "${MODE}" == "PE" && "${detected_type}" != "PE" ]]; then
        echo "[ERROR] Mode was set to PE, but file appears to be ${detected_type}: ${filename}" >&2
        exit 1
    fi

    if [[ "${MODE}" == "SE" && "${detected_type}" != "SE" ]]; then
        echo "[ERROR] Mode was set to SE, but file appears to be ${detected_type}: ${filename}" >&2
        exit 1
    fi
}

check_base_name_collisions() {
    declare -A seen=()
    local sam
    local base

    for sam in "$@"; do
        base="$(extract_base_name "${sam}")"

        if [[ -n "${seen[$base]:-}" ]]; then
            echo "[ERROR] Duplicate output base name detected: ${base}" >&2
            echo "        Conflicting files:" >&2
            echo "        - ${seen[$base]}" >&2
            echo "        - ${sam}" >&2
            echo "        Rename files or change the base-name extraction rule." >&2
            exit 1
        fi

        seen["$base"]="${sam}"
    done
}

count_reads() {
    local bamfile="$1"

    if [[ -f "${bamfile}" ]]; then
        run_docker_samtools view -@ "${THREADS}" -c "${bamfile}"
    else
        echo "NA"
    fi
}

count_mapped_reads() {
    local bamfile="$1"

    if [[ -f "${bamfile}" ]]; then
        run_docker_samtools view -@ "${THREADS}" -c -F 4 "${bamfile}"
    else
        echo "NA"
    fi
}

count_properly_paired_reads() {
    local bamfile="$1"

    if [[ -f "${bamfile}" ]]; then
        run_docker_samtools view -@ "${THREADS}" -c -f 3 "${bamfile}"
    else
        echo "NA"
    fi
}

write_summary_header() {
    cat > "${SUMMARY_FILE}" << EOF
sample	library_type	input_bam_reads	mapped_bam_reads	sorted_bam_reads	dedup_bam_reads	concordant_bam_reads	q20_bam_reads	mapped_reads_after_dedup	properly_paired_reads_after_dedup
EOF
}

append_summary_line() {
    local sample="$1"
    local libtype="$2"
    local fixed_bam="$3"
    local mapped_bam="$4"
    local sorted_bam="$5"
    local dedup_bam="$6"
    local concordant_bam="$7"
    local q20_bam="$8"

    local n_fixed
    local n_mapped_bam
    local n_sorted
    local n_dedup
    local n_concordant
    local n_q20
    local n_mapped_after_dedup
    local n_proper

    n_fixed="$(count_reads "${fixed_bam}")"
    n_mapped_bam="$(count_reads "${mapped_bam}")"
    n_sorted="$(count_reads "${sorted_bam}")"
    n_dedup="$(count_reads "${dedup_bam}")"
    n_concordant="$(count_reads "${concordant_bam}")"
    n_q20="$(count_reads "${q20_bam}")"
    n_mapped_after_dedup="$(count_mapped_reads "${dedup_bam}")"

    if [[ "${libtype}" == "PE" ]]; then
        n_proper="$(count_properly_paired_reads "${dedup_bam}")"
    else
        n_proper="NA"
    fi

    echo -e "${sample}\t${libtype}\t${n_fixed}\t${n_mapped_bam}\t${n_sorted}\t${n_dedup}\t${n_concordant}\t${n_q20}\t${n_mapped_after_dedup}\t${n_proper}" >> "${SUMMARY_FILE}"
}

###############################################################################
# Processing functions
###############################################################################

process_pe() {
    local samfile="$1"
    local base
    base="$(extract_base_name "${samfile}")"

    local fixed_bam="${FIXED_DIR}/${base}_PE_bt.bam"
    local mapped_bam="${MAPPED_DIR}/${base}_PE_mapped_bt.bam"
    local sorted_bam="${SORTED_DIR}/${base}_PE_mapped_sorted_bt.bam"
    local dedup_bam="${DEDUP_DIR}/${base}_PE_mapped_sorted_dedup_bt.bam"
    local concordant_bam="${CONCORDANT_DIR}/${base}_PE_mapped_sorted_dedup_concordant_bt.bam"
    local q20_bam="${Q20_DIR}/${base}_PE_mapped_sorted_dedup_q20_bt.bam"

    echo "=================================================="
    echo "[PE] Processing file: ${samfile}"
    echo "[PE] Sample name: ${base}"
    echo "=================================================="

    if file_ready "${fixed_bam}"; then
        echo "[PE] Step 1 skipped: ${fixed_bam} already exists"
    else
        echo "[PE] Step 1: name-sort + fixmate"
        run_docker_shell \
            "samtools sort -@ ${THREADS} -n -O sam '${samfile}' | samtools fixmate -@ ${THREADS} -m -O bam - '${fixed_bam}'"
    fi

    if [[ "${DELETE_SAM}" -eq 1 ]]; then
        if [[ -f "${samfile}" ]]; then
            echo "[PE] Step 2: removing original SAM"
            rm -f "${samfile}"
        else
            echo "[PE] Step 2 skipped: original SAM already absent"
        fi
    else
        echo "[PE] Step 2: keeping original SAM file"
    fi

    if file_ready "${mapped_bam}" && file_ready "${sorted_bam}"; then
        echo "[PE] Steps 3-4 skipped: mapped and sorted BAM already exist"
    elif file_ready "${mapped_bam}" && ! file_ready "${sorted_bam}"; then
        echo "[PE] Step 3 skipped: mapped BAM already exists"
        echo "[PE] Step 4: coordinate sorting"
        run_docker_samtools sort -@ "${THREADS}" "${mapped_bam}" -o "${sorted_bam}"
    else
        echo "[PE] Steps 3-4: selecting mapped reads and coordinate sorting"
        run_docker_shell \
            "samtools view -@ ${THREADS} -b -F 4 '${fixed_bam}' -o '${mapped_bam}' && samtools sort -@ ${THREADS} '${mapped_bam}' -o '${sorted_bam}'"
    fi

    if file_ready "${dedup_bam}"; then
        echo "[PE] Step 5 skipped: ${dedup_bam} already exists"
    else
        echo "[PE] Step 5: duplicate removal with markdup"
        run_docker_shell_markdup \
            "samtools markdup -@ ${THREADS} -r -S -f '${LOG_DIR}/${base}_PE_markdup.log' '${sorted_bam}' '${dedup_bam}'"
    fi

    if file_ready "${concordant_bam}" && file_ready "${q20_bam}"; then
        echo "[PE] Steps 6-7 skipped: concordant and q20 BAM already exist"
    elif file_ready "${concordant_bam}" && ! file_ready "${q20_bam}"; then
        echo "[PE] Step 6 skipped: concordant BAM already exists"
        echo "[PE] Step 7: selecting reads with MAPQ >= 20"
        run_docker_samtools view -@ "${THREADS}" -h -b -q 20 "${dedup_bam}" -o "${q20_bam}"
    elif [[ ! -f "${concordant_bam}" && -f "${q20_bam}" ]]; then
        echo "[PE] Step 7 skipped: q20 BAM already exists"
        echo "[PE] Step 6: selecting properly paired reads"
        run_docker_samtools view -@ "${THREADS}" -h -b -f 3 "${dedup_bam}" -o "${concordant_bam}"
    else
        echo "[PE] Steps 6-7: generating concordant and q20 BAM files"
        run_docker_shell \
            "samtools view -@ ${THREADS} -h -b -f 3 '${dedup_bam}' -o '${concordant_bam}' && samtools view -@ ${THREADS} -h -b -q 20 '${dedup_bam}' -o '${q20_bam}'"
    fi

    for bam in "${dedup_bam}" "${concordant_bam}" "${q20_bam}"; do
        if [[ -f "${bam}" && ! -f "${bam}.bai" ]]; then
            echo "[PE] Indexing: ${bam}"
            run_docker_samtools index -@ "${THREADS}" "${bam}"
        fi
    done

    if ! file_ready "${QC_DIR}/${base}_PE_quickcheck.txt"; then
        echo "[PE] Running quickcheck"
        run_docker_shell \
            "samtools quickcheck -v '${fixed_bam}' '${mapped_bam}' '${sorted_bam}' '${dedup_bam}' '${concordant_bam}' '${q20_bam}' > '${QC_DIR}/${base}_PE_quickcheck.txt' 2>&1 || true"
    fi

    for label in fixed mapped sorted dedup concordant q20; do
        case "$label" in
            fixed)      bam="${fixed_bam}" ;;
            mapped)     bam="${mapped_bam}" ;;
            sorted)     bam="${sorted_bam}" ;;
            dedup)      bam="${dedup_bam}" ;;
            concordant) bam="${concordant_bam}" ;;
            q20)        bam="${q20_bam}" ;;
        esac

        if ! file_ready "${QC_DIR}/${base}_PE_${label}.flagstat.txt"; then
            run_docker_samtools flagstat -@ "${THREADS}" "${bam}" > "${QC_DIR}/${base}_PE_${label}.flagstat.txt"
        fi
    done

    append_summary_line "${base}" "PE" "${fixed_bam}" "${mapped_bam}" "${sorted_bam}" "${dedup_bam}" "${concordant_bam}" "${q20_bam}"

    echo "[PE] Finished processing: ${base}"
    echo
}

process_se() {
    local samfile="$1"
    local base
    base="$(extract_base_name "${samfile}")"

    local fixed_bam="${FIXED_DIR}/${base}_SE_bt.bam"
    local mapped_bam="${MAPPED_DIR}/${base}_SE_mapped_bt.bam"
    local sorted_bam="${SORTED_DIR}/${base}_SE_mapped_sorted_bt.bam"
    local dedup_bam="${DEDUP_DIR}/${base}_SE_mapped_sorted_dedup_bt.bam"
    local q20_bam="${Q20_DIR}/${base}_SE_mapped_sorted_dedup_q20_bt.bam"

    echo "=================================================="
    echo "[SE] Processing file: ${samfile}"
    echo "[SE] Sample name: ${base}"
    echo "=================================================="

    if file_ready "${fixed_bam}"; then
        echo "[SE] Step 1 skipped: ${fixed_bam} already exists"
    else
        echo "[SE] Step 1: name-sort and convert to BAM"
        run_docker_samtools sort -@ "${THREADS}" -n -O bam "${samfile}" -o "${fixed_bam}"
    fi

    if [[ "${DELETE_SAM}" -eq 1 ]]; then
        if [[ -f "${samfile}" ]]; then
            echo "[SE] Step 2: removing original SAM"
            rm -f "${samfile}"
        else
            echo "[SE] Step 2 skipped: original SAM already absent"
        fi
    else
        echo "[SE] Step 2: keeping original SAM file"
    fi

    if file_ready "${mapped_bam}" && file_ready "${sorted_bam}"; then
        echo "[SE] Steps 3-4 skipped: mapped and sorted BAM already exist"
    elif file_ready "${mapped_bam}" && ! file_ready "${sorted_bam}"; then
        echo "[SE] Step 3 skipped: mapped BAM already exists"
        echo "[SE] Step 4: coordinate sorting"
        run_docker_samtools sort -@ "${THREADS}" "${mapped_bam}" -o "${sorted_bam}"
    else
        echo "[SE] Steps 3-4: selecting mapped reads and coordinate sorting"
        run_docker_shell \
            "samtools view -@ ${THREADS} -b -F 4 '${fixed_bam}' -o '${mapped_bam}' && samtools sort -@ ${THREADS} '${mapped_bam}' -o '${sorted_bam}'"
    fi

    if file_ready "${dedup_bam}"; then
        echo "[SE] Step 5 skipped: ${dedup_bam} already exists"
    else
        echo "[SE] Step 5: duplicate removal with markdup"
        run_docker_shell_markdup \
            "samtools markdup -@ ${THREADS} -r -S -f '${LOG_DIR}/${base}_SE_markdup.log' '${sorted_bam}' '${dedup_bam}'"
    fi

    echo "[SE] Step 6 skipped: concordant filtering is not applicable to single-end reads"

    if file_ready "${q20_bam}"; then
        echo "[SE] Step 7 skipped: ${q20_bam} already exists"
    else
        echo "[SE] Step 7: selecting reads with MAPQ >= 20"
        run_docker_samtools view -@ "${THREADS}" -h -b -q 20 "${dedup_bam}" -o "${q20_bam}"
    fi

    for bam in "${dedup_bam}" "${q20_bam}"; do
        if [[ -f "${bam}" && ! -f "${bam}.bai" ]]; then
            echo "[SE] Indexing: ${bam}"
            run_docker_samtools index -@ "${THREADS}" "${bam}"
        fi
    done

    if ! file_ready "${QC_DIR}/${base}_SE_quickcheck.txt"; then
        echo "[SE] Running quickcheck"
        run_docker_shell \
            "samtools quickcheck -v '${fixed_bam}' '${mapped_bam}' '${sorted_bam}' '${dedup_bam}' '${q20_bam}' > '${QC_DIR}/${base}_SE_quickcheck.txt' 2>&1 || true"
    fi

    for label in fixed mapped sorted dedup q20; do
        case "$label" in
            fixed)  bam="${fixed_bam}" ;;
            mapped) bam="${mapped_bam}" ;;
            sorted) bam="${sorted_bam}" ;;
            dedup)  bam="${dedup_bam}" ;;
            q20)    bam="${q20_bam}" ;;
        esac

        if ! file_ready "${QC_DIR}/${base}_SE_${label}.flagstat.txt"; then
            run_docker_samtools flagstat -@ "${THREADS}" "${bam}" > "${QC_DIR}/${base}_SE_${label}.flagstat.txt"
        fi
    done

    append_summary_line "${base}" "SE" "${fixed_bam}" "${mapped_bam}" "${sorted_bam}" "${dedup_bam}" "NA" "${q20_bam}"

    echo "[SE] Finished processing: ${base}"
    echo
}

###############################################################################
# Run pipeline
###############################################################################

write_summary_header

shopt -s nullglob
SAM_FILES=( *.sam )

if [[ ${#SAM_FILES[@]} -eq 0 ]]; then
    echo "[ERROR] No SAM files found in ${DIR}" >&2
    exit 1
fi

check_base_name_collisions "${SAM_FILES[@]}"

echo "Working directory: $(pwd)"
echo "Threads: ${THREADS}"
echo "Mode: ${MODE}"
echo "Docker image: ${DOCKER_IMAGE}"
echo "Docker user: ${DOCKER_UIDGID}"
echo "markdup Docker memory limit: ${MARKDUP_MEMORY}"

if [[ "${DELETE_SAM}" -eq 1 ]]; then
    echo "Delete SAM files: yes"
else
    echo "Delete SAM files: no"
fi

echo "SAM files found: ${#SAM_FILES[@]}"
echo

for sam in "${SAM_FILES[@]}"; do
    detected_type="$(detect_library_type "${sam}")"
    validate_mode_vs_filetype "${detected_type}" "${sam}"

    if [[ "${detected_type}" == "PE" ]]; then
        process_pe "${sam}"
    elif [[ "${detected_type}" == "SE" ]]; then
        process_se "${sam}"
    else
        echo "[ERROR] Unexpected library type for file: ${sam}" >&2
        exit 1
    fi
done

echo "=================================================="
echo "Pipeline completed successfully."
echo
echo "Output directories:"
echo "  ${FIXED_DIR}/       -> BAM after initial conversion"
echo "  ${MAPPED_DIR}/      -> mapped reads only"
echo "  ${SORTED_DIR}/      -> coordinate-sorted BAM"
echo "  ${DEDUP_DIR}/       -> deduplicated BAM"
echo "  ${CONCORDANT_DIR}/  -> concordant reads, PE only"
echo "  ${Q20_DIR}/         -> reads with MAPQ >= 20"
echo "  ${LOG_DIR}/         -> duplicate-removal logs"
echo "  ${QC_DIR}/          -> quickcheck and flagstat reports"
echo "  ${SUMMARY_FILE}     -> unified tabular summary"
echo "=================================================="
